### PR TITLE
Customizable "nerd" folder

### PR DESCRIPTION
**Pull request by maxim**
The simplest way to make "nerd" customizable. Doesn't affect any existing workflows.

### CODE REVIEW

**Comment by zenspider** [comment]
nice!

Makes me wonder if it shouldn't be on a per-source basis (eg nerd vs work).

**Comment by maxim** [comment]
@zenspider would be ideal, but I'm thinking this change doesn't stand in the way of that. Besides, it's easier to think of this folder as your "sync inbox" and move stuff away from it yourself, just matters that it's all pulled in. You throw a line into your shell's rc, and now your sync inbox folder is named as you like.

**Comment by maxim** [comment]
Although I'm not sure if moving stuff out of the folder will break sync, I want to use this project, but haven't gotten it setup fully to my liking just yet.

**Comment by zenspider** [comment]
What else are you looking for?

You might want to read my "productivity pr0n" series of blog posts to see some of the reasoning behind some of this stuff.

**Comment by maxim** [comment]
Just read it, it's full of awesome. For me the most important thing is sustainability, wouldn't want to bite off more than I can chew (e.g. take all your advice, and not able to keep up with it). To avoid that I'm paving my own way gradually, and right now what works for me is something like the following:

* have everything in omnifocus (organized by project/context to the best of my patience)
* every day flag a bunch of items I want to do today, that's it

So with the sync I'm just trying to achieve the former. I'm not sure if I can organize stuff after I synced it without it automatically re-syncing the same stuff again. Will that work? Can sync act like an inbox, from which I move stuff away after having it synced? Or does it have to sit there for sync to find it?

**Comment by zenspider** [comment]
Merged. I'm gonna take a pass at a bit of cleanup.

BTS = Bug tracking service? I'm tempted to remove that acronym unless you see a reason for it.

**Comment by maxim** [comment]
I was trying to follow your terminology while avoiding the word `nerd` in ENV vars. I used `NERD_FOLDER` in code because it's already used in some variable names, and changing terminology is not the point of this PR, just wanted to keep the diff as small as possible. Ideally would get rid of both BTS and "nerd".

**Pull request closed without merging**
